"""
Observability baseline — structured JSON logging + Prometheus metrics.

This module provides the three building blocks that give ECM operators an
honest answer to "what just happened?":

1. A trace-id contextvar so every log line within a request shares a single
   correlation key (read from the inbound ``X-Request-ID`` header when
   present, else a fresh UUIDv4 generated by the correlation middleware).

2. A JSON log formatter + stdlib ``logging.Filter`` that binds ``trace_id``
   (plus any ad-hoc context set via :func:`bind_context`) onto every
   :class:`logging.LogRecord`. The result is one line of machine-parseable
   JSON per log event — no grep-and-pray across multi-line tracebacks.

3. Prometheus metrics — counters/histograms for HTTP traffic and gauges for
   the readiness endpoint. The HTTP middleware labels by route *pattern*
   (``/api/channels/{channel_id}``), never raw path, so cardinality stays
   bounded regardless of traffic mix. Readiness sub-checks get a bounded
   ``check`` label that matches the keys returned by the readiness probe.

Conventions (enforced here, documented in ``docs/backend_architecture.md``):

- Metric naming: ``ecm_<subsystem>_<name>_<unit>`` (snake_case, unit suffix).
- Label cardinality: bounded sets only. Never ``user_id``, ``trace_id``,
  or raw paths. Per-request correlation belongs in logs, not metric labels.
- Required log fields: ``ts``, ``level``, ``logger``, ``msg``, ``trace_id``.
  Extra fields flow through ``bind_context`` (e.g. ``restore_id``,
  ``sync_id``, ``phase``).

The :func:`install_observability` function is the single entry point —
``main.py`` calls it once at import time and everything else is wired up.
"""
from __future__ import annotations

import contextvars
import json
import logging
import time
import uuid
from typing import Any, Callable, Dict, Optional

try:  # pragma: no cover — defensive for environments without prometheus-client
    from prometheus_client import (
        CONTENT_TYPE_LATEST,
        CollectorRegistry,
        Counter,
        Gauge,
        Histogram,
        generate_latest,
    )
except ImportError:  # pragma: no cover
    CONTENT_TYPE_LATEST = "text/plain"
    CollectorRegistry = None  # type: ignore[assignment]
    Counter = None  # type: ignore[assignment]
    Gauge = None  # type: ignore[assignment]
    Histogram = None  # type: ignore[assignment]
    generate_latest = None  # type: ignore[assignment]


# =========================================================================
# Trace-id + bound-context plumbing
# =========================================================================
# Why a contextvar? Async request handlers cannot rely on thread-local
# storage — an ``asyncio`` task may hop between threads. A contextvar is
# propagated correctly through ``await`` boundaries and task spawning
# (``asyncio.create_task`` copies the current context), which is exactly the
# semantics the correlation middleware needs.
_trace_id_var: contextvars.ContextVar[Optional[str]] = contextvars.ContextVar(
    "ecm_trace_id", default=None
)
_bound_context_var: contextvars.ContextVar[Dict[str, Any]] = contextvars.ContextVar(
    "ecm_bound_context", default={}
)


def get_trace_id() -> Optional[str]:
    """Return the current request's trace id, or ``None`` outside a request."""
    return _trace_id_var.get()


def set_trace_id(trace_id: str) -> contextvars.Token:
    """Set the trace id for the current context. Returns a reset token."""
    return _trace_id_var.set(trace_id)


def reset_trace_id(token: contextvars.Token) -> None:
    """Reset the trace id using a token from :func:`set_trace_id`."""
    _trace_id_var.reset(token)


def bind_context(**fields: Any) -> contextvars.Token:
    """Attach key/value pairs to every log line in the current context.

    Typical use — a long-running restore job binds ``restore_id`` at the top,
    so every log line inside the task carries it without the call sites
    having to thread it through::

        token = bind_context(restore_id=restore.id, phase="validate")
        try:
            run_validation()
        finally:
            reset_context(token)

    The returned token can be passed to :func:`reset_context` to pop the
    binding (e.g. in a ``finally`` clause or a context manager).
    """
    current = dict(_bound_context_var.get())
    current.update(fields)
    return _bound_context_var.set(current)


def reset_context(token: contextvars.Token) -> None:
    """Undo a prior :func:`bind_context` call."""
    _bound_context_var.reset(token)


def generate_trace_id() -> str:
    """Return a fresh UUIDv4 string suitable for use as a trace id."""
    return str(uuid.uuid4())


# =========================================================================
# JSON logging
# =========================================================================
class _TraceIdFilter(logging.Filter):
    """Attach ``trace_id`` and any bound context to each log record.

    Runs as a filter (not a formatter) so the metadata is available to any
    formatter the operator plugs in downstream — including the JSON
    formatter we install below and any custom handlers that might want to
    consume structured attributes directly.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        record.trace_id = _trace_id_var.get() or "-"
        bound = _bound_context_var.get()
        if bound:
            for key, value in bound.items():
                # Don't let bound context clobber reserved LogRecord attrs
                # (``message``, ``asctime``, etc.) — namespace-collide defensively.
                if not hasattr(record, key):
                    setattr(record, key, value)
        return True


# Fields we already represent explicitly in the JSON payload — skip them in
# the generic "extra" sweep so we don't double-emit.
_STANDARD_LOGRECORD_FIELDS = frozenset(
    {
        "name", "msg", "args", "levelname", "levelno", "pathname", "filename",
        "module", "exc_info", "exc_text", "stack_info", "lineno", "funcName",
        "created", "msecs", "relativeCreated", "thread", "threadName",
        "processName", "process", "message", "asctime", "taskName",
    }
)


class JsonFormatter(logging.Formatter):
    """Emit each log record as a single-line JSON document.

    Required fields — ``ts``, ``level``, ``logger``, ``msg``, ``trace_id`` —
    are always present. Any extra attributes attached to the LogRecord (via
    ``logger.info("...", extra={...})`` or :func:`bind_context`) flow into
    the top-level JSON object so downstream log pipelines can index on them
    without custom parsing.
    """

    def format(self, record: logging.LogRecord) -> str:  # noqa: A003 — stdlib signature
        payload: Dict[str, Any] = {
            "ts": self.formatTime(record, datefmt="%Y-%m-%dT%H:%M:%S") + f".{int(record.msecs):03d}Z",
            "level": record.levelname,
            "logger": record.name,
            "msg": record.getMessage(),
            "trace_id": getattr(record, "trace_id", "-"),
        }
        if record.exc_info:
            payload["exc_info"] = self.formatException(record.exc_info)
        if record.stack_info:
            payload["stack_info"] = self.formatStack(record.stack_info)

        # Sweep in any extra attributes (bound context, explicit extras).
        for key, value in record.__dict__.items():
            if key in _STANDARD_LOGRECORD_FIELDS or key == "trace_id":
                continue
            try:
                json.dumps(value)  # fast check for serializability
                payload[key] = value
            except (TypeError, ValueError):
                payload[key] = repr(value)

        return json.dumps(payload, default=str, separators=(",", ":"))


def install_json_logging(level: int = logging.INFO) -> None:
    """Swap the root logger's handlers for a JSON-emitting stream handler.

    Idempotent — calling twice leaves a single JSON handler in place. The
    ``_TraceIdFilter`` is applied on both the handler and the root logger
    so the trace id survives regardless of whether a subclassed logger adds
    its own handler.
    """
    root = logging.getLogger()
    json_handler = logging.StreamHandler()
    json_handler.setFormatter(JsonFormatter())
    json_handler.addFilter(_TraceIdFilter())

    # Drop any handler we previously installed (idempotency).
    for existing in list(root.handlers):
        if getattr(existing, "_ecm_json_handler", False):
            root.removeHandler(existing)
        else:
            # Also replace the formatter on any default stream handler so
            # ``logging.basicConfig``-installed handlers speak JSON too,
            # instead of emitting a second plaintext line alongside ours.
            if isinstance(existing, logging.StreamHandler):
                existing.setFormatter(JsonFormatter())
                existing.addFilter(_TraceIdFilter())

    json_handler._ecm_json_handler = True  # type: ignore[attr-defined]
    root.addHandler(json_handler)
    root.addFilter(_TraceIdFilter())
    root.setLevel(level)


# =========================================================================
# Prometheus metrics
# =========================================================================
# A dedicated registry keeps ECM metrics isolated from any collectors a
# third-party library might have auto-registered on ``REGISTRY``. Tests can
# build a fresh registry to avoid "Duplicated timeseries in CollectorRegistry"
# errors when re-importing the module.
REGISTRY: Optional[CollectorRegistry] = None
_METRICS: Dict[str, Any] = {}


# Latency histogram buckets — tuned for a local web app hitting SQLite +
# a LAN Dispatcharr instance. Most requests land under 100 ms; the long
# tail past 5 s captures the pathological "something went wrong" cases.
_HTTP_LATENCY_BUCKETS = (
    0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0,
)
_HEALTH_CHECK_BUCKETS = (
    0.001, 0.005, 0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 3.0,
)


def _build_metrics(registry: CollectorRegistry) -> Dict[str, Any]:
    """Instantiate the ECM metric set against ``registry``."""
    return {
        "http_requests_total": Counter(
            "ecm_http_requests_total",
            "Count of HTTP requests processed, labeled by method, route "
            "pattern, and response status code.",
            ["method", "path", "status"],
            registry=registry,
        ),
        "http_request_duration_seconds": Histogram(
            "ecm_http_request_duration_seconds",
            "HTTP request latency in seconds, labeled by method and route "
            "pattern. Buckets cover sub-10ms up to 10s outliers.",
            ["method", "path"],
            buckets=_HTTP_LATENCY_BUCKETS,
            registry=registry,
        ),
        "health_ready_ok": Gauge(
            "ecm_health_ready_ok",
            "1 when /api/health/ready reports all subsystems healthy, else 0. "
            "Last evaluated value — the readiness endpoint updates this on each call.",
            registry=registry,
        ),
        "health_ready_check_duration_seconds": Histogram(
            "ecm_health_ready_check_duration_seconds",
            "Duration of each readiness sub-check (database, dispatcharr, ffprobe).",
            ["check"],
            buckets=_HEALTH_CHECK_BUCKETS,
            registry=registry,
        ),
    }


def install_metrics(registry: Optional[CollectorRegistry] = None) -> Dict[str, Any]:
    """Create the metric set on ``registry`` (or a fresh registry).

    Returns the populated ``_METRICS`` dict. Subsequent calls reuse the
    existing registry — the registry is process-global because Prometheus
    clients collate samples from it at scrape time.
    """
    global REGISTRY, _METRICS
    if REGISTRY is None:
        REGISTRY = registry or CollectorRegistry()
        _METRICS = _build_metrics(REGISTRY)
    return _METRICS


def get_metric(name: str) -> Any:
    """Return the metric object registered under ``name`` (e.g. ``"http_requests_total"``)."""
    if not _METRICS:
        install_metrics()
    return _METRICS[name]


def render_metrics() -> bytes:
    """Return the Prometheus text-format exposition of the current registry."""
    if REGISTRY is None:
        install_metrics()
    return generate_latest(REGISTRY)


def reset_for_tests() -> None:
    """Drop the current registry — used by tests that rebuild it per case."""
    global REGISTRY, _METRICS
    REGISTRY = None
    _METRICS = {}


# =========================================================================
# Single entry point wired from main.py
# =========================================================================
def install_observability(level: int = logging.INFO) -> None:
    """Install JSON logging + the Prometheus metric set.

    Call exactly once during application startup. Safe to call multiple
    times — both sub-installers are idempotent.
    """
    install_json_logging(level=level)
    install_metrics()
