"""baseline_initial_schema

Revision ID: 0001
Revises: 
Create Date: 2026-04-20 20:34:06.408423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_methods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('method_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('notify_info', sa.Boolean(), nullable=False),
    sa.Column('notify_success', sa.Boolean(), nullable=False),
    sa.Column('notify_warning', sa.Boolean(), nullable=False),
    sa.Column('notify_error', sa.Boolean(), nullable=False),
    sa.Column('alert_sources', sa.Text(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_methods', schema=None) as batch_op:
        batch_op.create_index('idx_alert_method_enabled', ['enabled'], unique=False)
        batch_op.create_index('idx_alert_method_type', ['method_type'], unique=False)

    op.create_table('auto_creation_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('m3u_account_id', sa.Integer(), nullable=True),
    sa.Column('target_group_id', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.Column('actions', sa.Text(), nullable=False),
    sa.Column('run_on_refresh', sa.Boolean(), nullable=False),
    sa.Column('stop_on_first_match', sa.Boolean(), nullable=False),
    sa.Column('sort_field', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.String(length=4), nullable=True),
    sa.Column('probe_on_sort', sa.Boolean(), nullable=False),
    sa.Column('sort_regex', sa.String(length=500), nullable=True),
    sa.Column('stream_sort_field', sa.String(length=50), nullable=True),
    sa.Column('stream_sort_order', sa.String(length=4), nullable=True),
    sa.Column('normalization_group_ids', sa.Text(), nullable=True),
    sa.Column('skip_struck_streams', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_stats', sa.Text(), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.Column('managed_channel_ids', sa.Text(), nullable=True),
    sa.Column('orphan_action', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auto_creation_rules', schema=None) as batch_op:
        batch_op.create_index('idx_auto_rule_enabled', ['enabled'], unique=False)
        batch_op.create_index('idx_auto_rule_enabled_priority', ['enabled', 'priority'], unique=False)
        batch_op.create_index('idx_auto_rule_m3u_account', ['m3u_account_id'], unique=False)
        batch_op.create_index('idx_auto_rule_priority', ['priority'], unique=False)
        batch_op.create_index('idx_auto_rule_run_on_refresh', ['run_on_refresh'], unique=False)

    op.create_table('bandwidth_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bytes_transferred', sa.BigInteger(), nullable=False),
    sa.Column('bytes_in', sa.BigInteger(), nullable=False),
    sa.Column('bytes_out', sa.BigInteger(), nullable=False),
    sa.Column('peak_channels', sa.Integer(), nullable=False),
    sa.Column('peak_clients', sa.Integer(), nullable=False),
    sa.Column('peak_bitrate_in', sa.BigInteger(), nullable=False),
    sa.Column('peak_bitrate_out', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    with op.batch_alter_table('bandwidth_daily', schema=None) as batch_op:
        batch_op.create_index('idx_bandwidth_daily_date', [sa.literal_column('date DESC')], unique=False)

    op.create_table('channel_bandwidth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bytes_transferred', sa.BigInteger(), nullable=False),
    sa.Column('peak_clients', sa.Integer(), nullable=False),
    sa.Column('total_watch_seconds', sa.Integer(), nullable=False),
    sa.Column('connection_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'date', name='uq_channel_bandwidth_channel_date')
    )
    with op.batch_alter_table('channel_bandwidth', schema=None) as batch_op:
        batch_op.create_index('idx_channel_bandwidth_bytes', [sa.literal_column('bytes_transferred DESC')], unique=False)
        batch_op.create_index('idx_channel_bandwidth_channel', ['channel_id'], unique=False)
        batch_op.create_index('idx_channel_bandwidth_date', [sa.literal_column('date DESC')], unique=False)

    op.create_table('channel_popularity_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('watch_count_7d', sa.Integer(), nullable=False),
    sa.Column('watch_time_7d', sa.Integer(), nullable=False),
    sa.Column('unique_viewers_7d', sa.Integer(), nullable=False),
    sa.Column('bandwidth_7d', sa.BigInteger(), nullable=False),
    sa.Column('trend', sa.String(length=10), nullable=False),
    sa.Column('trend_percent', sa.Float(), nullable=False),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('previous_rank', sa.Integer(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    with op.batch_alter_table('channel_popularity_scores', schema=None) as batch_op:
        batch_op.create_index('idx_popularity_channel', ['channel_id'], unique=False)
        batch_op.create_index('idx_popularity_rank', ['rank'], unique=False)
        batch_op.create_index('idx_popularity_score', [sa.literal_column('score DESC')], unique=False)
        batch_op.create_index('idx_popularity_trend', ['trend'], unique=False)

    op.create_table('channel_watch_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('watch_count', sa.Integer(), nullable=False),
    sa.Column('total_watch_seconds', sa.Integer(), nullable=False),
    sa.Column('last_watched', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    with op.batch_alter_table('channel_watch_stats', schema=None) as batch_op:
        batch_op.create_index('idx_channel_watch_channel_id', ['channel_id'], unique=False)
        batch_op.create_index('idx_channel_watch_count', [sa.literal_column('watch_count DESC')], unique=False)
        batch_op.create_index('idx_channel_watch_time', [sa.literal_column('total_watch_seconds DESC')], unique=False)

    op.create_table('cloud_storage_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.String(length=20), nullable=False),
    sa.Column('credentials', sa.Text(), nullable=False),
    sa.Column('upload_path', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dummy_epg_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('name_source', sa.String(length=20), nullable=False),
    sa.Column('stream_index', sa.Integer(), nullable=False),
    sa.Column('title_pattern', sa.String(length=500), nullable=True),
    sa.Column('time_pattern', sa.String(length=500), nullable=True),
    sa.Column('date_pattern', sa.String(length=500), nullable=True),
    sa.Column('substitution_pairs', sa.Text(), nullable=True),
    sa.Column('title_template', sa.String(length=500), nullable=True),
    sa.Column('description_template', sa.Text(), nullable=True),
    sa.Column('upcoming_title_template', sa.String(length=500), nullable=True),
    sa.Column('upcoming_description_template', sa.Text(), nullable=True),
    sa.Column('ended_title_template', sa.String(length=500), nullable=True),
    sa.Column('ended_description_template', sa.Text(), nullable=True),
    sa.Column('fallback_title_template', sa.String(length=500), nullable=True),
    sa.Column('fallback_description_template', sa.Text(), nullable=True),
    sa.Column('event_timezone', sa.String(length=50), nullable=False),
    sa.Column('output_timezone', sa.String(length=50), nullable=True),
    sa.Column('program_duration', sa.Integer(), nullable=False),
    sa.Column('categories', sa.String(length=500), nullable=True),
    sa.Column('channel_logo_url_template', sa.String(length=500), nullable=True),
    sa.Column('program_poster_url_template', sa.String(length=500), nullable=True),
    sa.Column('tvg_id_template', sa.String(length=255), nullable=False),
    sa.Column('include_date_tag', sa.Boolean(), nullable=False),
    sa.Column('include_live_tag', sa.Boolean(), nullable=False),
    sa.Column('include_new_tag', sa.Boolean(), nullable=False),
    sa.Column('pattern_builder_examples', sa.Text(), nullable=True),
    sa.Column('pattern_variants', sa.Text(), nullable=True),
    sa.Column('channel_group_ids', sa.Text(), nullable=True),
    sa.Column('last_generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dummy_epg_profiles', schema=None) as batch_op:
        batch_op.create_index('idx_dummy_epg_profile_enabled', ['enabled'], unique=False)

    op.create_table('ffmpeg_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ffmpeg_profiles', schema=None) as batch_op:
        batch_op.create_index('idx_ffmpeg_profiles_created', [sa.literal_column('created_at DESC')], unique=False)

    op.create_table('ffmpeg_saved_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hidden_channel_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('hidden_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id')
    )
    with op.batch_alter_table('hidden_channel_groups', schema=None) as batch_op:
        batch_op.create_index('idx_hidden_group_id', ['group_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('before_value', sa.Text(), nullable=True),
    sa.Column('after_value', sa.Text(), nullable=True),
    sa.Column('user_initiated', sa.Boolean(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index('idx_journal_action_type', ['action_type'], unique=False)
        batch_op.create_index('idx_journal_category', ['category'], unique=False)
        batch_op.create_index('idx_journal_timestamp', [sa.literal_column('timestamp DESC')], unique=False)

    op.create_table('lookup_tables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entries', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('lookup_tables', schema=None) as batch_op:
        batch_op.create_index('idx_lookup_table_name', ['name'], unique=False)

    op.create_table('m3u_digest_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('email_recipients', sa.Text(), nullable=True),
    sa.Column('include_group_changes', sa.Boolean(), nullable=False),
    sa.Column('include_stream_changes', sa.Boolean(), nullable=False),
    sa.Column('show_detailed_list', sa.Boolean(), nullable=False),
    sa.Column('min_changes_threshold', sa.Integer(), nullable=False),
    sa.Column('send_to_discord', sa.Boolean(), nullable=False),
    sa.Column('exclude_group_patterns', sa.Text(), nullable=True),
    sa.Column('exclude_stream_patterns', sa.Text(), nullable=True),
    sa.Column('last_digest_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m3u_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('m3u_account_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('groups_data', sa.Text(), nullable=True),
    sa.Column('total_streams', sa.Integer(), nullable=False),
    sa.Column('dispatcharr_updated_at', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('m3u_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_m3u_snapshot_account', ['m3u_account_id'], unique=False)
        batch_op.create_index('idx_m3u_snapshot_account_time', ['m3u_account_id', sa.literal_column('snapshot_time DESC')], unique=False)
        batch_op.create_index('idx_m3u_snapshot_time', [sa.literal_column('snapshot_time DESC')], unique=False)

    op.create_table('normalization_rule_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('normalization_rule_groups', schema=None) as batch_op:
        batch_op.create_index('idx_norm_group_enabled', ['enabled'], unique=False)
        batch_op.create_index('idx_norm_group_priority', ['priority'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('action_label', sa.String(length=50), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notification_created_at', [sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index('idx_notification_read', ['read'], unique=False)
        batch_op.create_index('idx_notification_source', ['source'], unique=False)
        batch_op.create_index('idx_notification_type', ['type'], unique=False)

    op.create_table('playlist_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('selection_mode', sa.String(length=20), nullable=False),
    sa.Column('selected_groups', sa.Text(), nullable=False),
    sa.Column('selected_channels', sa.Text(), nullable=False),
    sa.Column('stream_url_mode', sa.String(length=20), nullable=False),
    sa.Column('include_logos', sa.Boolean(), nullable=False),
    sa.Column('include_epg_ids', sa.Boolean(), nullable=False),
    sa.Column('include_channel_numbers', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.String(length=20), nullable=False),
    sa.Column('filename_prefix', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('schedule_time', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('send_alerts', sa.Boolean(), nullable=False),
    sa.Column('alert_on_success', sa.Boolean(), nullable=False),
    sa.Column('alert_on_warning', sa.Boolean(), nullable=False),
    sa.Column('alert_on_error', sa.Boolean(), nullable=False),
    sa.Column('alert_on_info', sa.Boolean(), nullable=False),
    sa.Column('send_to_email', sa.Boolean(), nullable=False),
    sa.Column('send_to_discord', sa.Boolean(), nullable=False),
    sa.Column('send_to_telegram', sa.Boolean(), nullable=False),
    sa.Column('show_notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_scheduled_task_enabled', ['enabled'], unique=False)
        batch_op.create_index('idx_scheduled_task_id', ['task_id'], unique=False)
        batch_op.create_index('idx_scheduled_task_next_run', ['next_run_at'], unique=False)

    op.create_table('stream_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('stream_name', sa.String(length=255), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('fps', sa.String(length=20), nullable=True),
    sa.Column('video_codec', sa.String(length=50), nullable=True),
    sa.Column('audio_codec', sa.String(length=50), nullable=True),
    sa.Column('audio_channels', sa.Integer(), nullable=True),
    sa.Column('stream_type', sa.String(length=20), nullable=True),
    sa.Column('bitrate', sa.BigInteger(), nullable=True),
    sa.Column('video_bitrate', sa.BigInteger(), nullable=True),
    sa.Column('probe_status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('last_probed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('is_black_screen', sa.Boolean(), nullable=False),
    sa.Column('is_low_fps', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stream_id')
    )
    with op.batch_alter_table('stream_stats', schema=None) as batch_op:
        batch_op.create_index('idx_stream_stats_last_probed', [sa.literal_column('last_probed DESC')], unique=False)
        batch_op.create_index('idx_stream_stats_probe_status', ['probe_status'], unique=False)
        batch_op.create_index('idx_stream_stats_stream_id', ['stream_id'], unique=False)

    op.create_table('tag_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('tag_groups', schema=None) as batch_op:
        batch_op.create_index('idx_tag_group_builtin', ['is_builtin'], unique=False)
        batch_op.create_index('idx_tag_group_name', ['name'], unique=False)

    op.create_table('task_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_executions', schema=None) as batch_op:
        batch_op.create_index('idx_task_exec_started_at', [sa.literal_column('started_at DESC')], unique=False)
        batch_op.create_index('idx_task_exec_status', ['status'], unique=False)
        batch_op.create_index('idx_task_exec_task_id', ['task_id'], unique=False)

    op.create_table('task_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('schedule_time', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('days_of_week', sa.String(length=20), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('week_parity', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_schedules', schema=None) as batch_op:
        batch_op.create_index('idx_task_schedule_enabled', ['enabled'], unique=False)
        batch_op.create_index('idx_task_schedule_next_run', ['next_run_at'], unique=False)
        batch_op.create_index('idx_task_schedule_task_id', ['task_id'], unique=False)

    op.create_table('unique_client_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.Column('watch_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unique_client_connections', schema=None) as batch_op:
        batch_op.create_index('idx_unique_client_channel', ['channel_id'], unique=False)
        batch_op.create_index('idx_unique_client_channel_date', ['channel_id', 'date'], unique=False)
        batch_op.create_index('idx_unique_client_channel_ip_date', ['channel_id', 'ip_address', 'date'], unique=False)
        batch_op.create_index('idx_unique_client_date', [sa.literal_column('date DESC')], unique=False)
        batch_op.create_index('idx_unique_client_ip', ['ip_address'], unique=False)
        batch_op.create_index('idx_unique_client_ip_date', ['ip_address', 'date'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_auth_provider', ['auth_provider'], unique=False)
        batch_op.create_index('idx_user_external_id', ['auth_provider', 'external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('auto_creation_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('rule_name', sa.String(length=100), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('streams_evaluated', sa.Integer(), nullable=False),
    sa.Column('streams_matched', sa.Integer(), nullable=False),
    sa.Column('channels_created', sa.Integer(), nullable=False),
    sa.Column('channels_updated', sa.Integer(), nullable=False),
    sa.Column('groups_created', sa.Integer(), nullable=False),
    sa.Column('streams_merged', sa.Integer(), nullable=False),
    sa.Column('streams_skipped', sa.Integer(), nullable=False),
    sa.Column('streams_excluded', sa.Integer(), nullable=False),
    sa.Column('created_entities', sa.Text(), nullable=True),
    sa.Column('modified_entities', sa.Text(), nullable=True),
    sa.Column('dry_run_results', sa.Text(), nullable=True),
    sa.Column('execution_log', sa.Text(), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(), nullable=True),
    sa.Column('rolled_back_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['auto_creation_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auto_creation_executions', schema=None) as batch_op:
        batch_op.create_index('idx_auto_exec_mode', ['mode'], unique=False)
        batch_op.create_index('idx_auto_exec_rule', ['rule_id'], unique=False)
        batch_op.create_index('idx_auto_exec_started', [sa.literal_column('started_at DESC')], unique=False)
        batch_op.create_index('idx_auto_exec_status', ['status'], unique=False)
        batch_op.create_index('idx_auto_exec_triggered_by', ['triggered_by'], unique=False)

    op.create_table('dummy_epg_channel_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('tvg_id_override', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['dummy_epg_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'channel_id', name='uq_dummy_epg_profile_channel')
    )
    with op.batch_alter_table('dummy_epg_channel_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_dummy_epg_channel_id', ['channel_id'], unique=False)
        batch_op.create_index('idx_dummy_epg_profile_id', ['profile_id'], unique=False)

    op.create_table('m3u_change_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('m3u_account_id', sa.Integer(), nullable=False),
    sa.Column('change_time', sa.DateTime(), nullable=False),
    sa.Column('change_type', sa.String(length=30), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('stream_names', sa.Text(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['m3u_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('m3u_change_logs', schema=None) as batch_op:
        batch_op.create_index('idx_m3u_change_account', ['m3u_account_id'], unique=False)
        batch_op.create_index('idx_m3u_change_account_time', ['m3u_account_id', sa.literal_column('change_time DESC')], unique=False)
        batch_op.create_index('idx_m3u_change_time', [sa.literal_column('change_time DESC')], unique=False)
        batch_op.create_index('idx_m3u_change_type', ['change_type'], unique=False)

    op.create_table('normalization_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('condition_type', sa.String(length=20), nullable=True),
    sa.Column('condition_value', sa.String(length=500), nullable=True),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('tag_group_id', sa.Integer(), nullable=True),
    sa.Column('tag_match_position', sa.String(length=20), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('condition_logic', sa.String(length=3), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('action_value', sa.String(length=500), nullable=True),
    sa.Column('else_action_type', sa.String(length=20), nullable=True),
    sa.Column('else_action_value', sa.String(length=500), nullable=True),
    sa.Column('stop_processing', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tag_group_id'], ['tag_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('normalization_rules', schema=None) as batch_op:
        batch_op.create_index('idx_norm_rule_enabled', ['enabled'], unique=False)
        batch_op.create_index('idx_norm_rule_group', ['group_id'], unique=False)
        batch_op.create_index('idx_norm_rule_priority', ['group_id', 'priority'], unique=False)
        batch_op.create_index('idx_norm_rule_tag_group', ['tag_group_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_reset_token_hash', ['token_hash'], unique=False)
        batch_op.create_index('idx_reset_token_user', ['user_id'], unique=False)

    op.create_table('publish_configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('event_triggers', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['playlist_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['cloud_storage_targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publish_configurations', schema=None) as batch_op:
        batch_op.create_index('idx_publish_config_profile', ['profile_id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['tag_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'value', name='uq_tag_group_value')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('idx_tag_enabled', ['enabled'], unique=False)
        batch_op.create_index('idx_tag_group_id', ['group_id'], unique=False)

    op.create_table('user_identities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_identity_provider_external'),
    sa.UniqueConstraint('provider', 'identifier', name='uq_identity_provider_identifier')
    )
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.create_index('idx_identity_external_id', ['provider', 'external_id'], unique=False)
        batch_op.create_index('idx_identity_identifier', ['provider', 'identifier'], unique=False)
        batch_op.create_index('idx_identity_provider', ['provider'], unique=False)
        batch_op.create_index('idx_identity_user_id', ['user_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_session_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_session_token_hash', ['refresh_token_hash'], unique=False)
        batch_op.create_index('idx_session_user', ['user_id'], unique=False)

    op.create_table('auto_creation_conflicts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('stream_name', sa.String(length=255), nullable=True),
    sa.Column('winning_rule_id', sa.Integer(), nullable=True),
    sa.Column('losing_rule_ids', sa.Text(), nullable=True),
    sa.Column('conflict_type', sa.String(length=30), nullable=False),
    sa.Column('resolution', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['auto_creation_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auto_creation_conflicts', schema=None) as batch_op:
        batch_op.create_index('idx_auto_conflict_execution', ['execution_id'], unique=False)
        batch_op.create_index('idx_auto_conflict_stream', ['stream_id'], unique=False)
        batch_op.create_index('idx_auto_conflict_type', ['conflict_type'], unique=False)
        batch_op.create_index('idx_auto_conflict_winning_rule', ['winning_rule_id'], unique=False)

    op.create_table('publish_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('channels_count', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['publish_configurations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publish_history', schema=None) as batch_op:
        batch_op.create_index('idx_publish_history_config', ['config_id'], unique=False)
        batch_op.create_index('idx_publish_history_started', [sa.literal_column('started_at DESC')], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publish_history', schema=None) as batch_op:
        batch_op.drop_index('idx_publish_history_started')
        batch_op.drop_index('idx_publish_history_config')

    op.drop_table('publish_history')
    with op.batch_alter_table('auto_creation_conflicts', schema=None) as batch_op:
        batch_op.drop_index('idx_auto_conflict_winning_rule')
        batch_op.drop_index('idx_auto_conflict_type')
        batch_op.drop_index('idx_auto_conflict_stream')
        batch_op.drop_index('idx_auto_conflict_execution')

    op.drop_table('auto_creation_conflicts')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_session_user')
        batch_op.drop_index('idx_session_token_hash')
        batch_op.drop_index('idx_session_expires')

    op.drop_table('user_sessions')
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.drop_index('idx_identity_user_id')
        batch_op.drop_index('idx_identity_provider')
        batch_op.drop_index('idx_identity_identifier')
        batch_op.drop_index('idx_identity_external_id')

    op.drop_table('user_identities')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('idx_tag_group_id')
        batch_op.drop_index('idx_tag_enabled')

    op.drop_table('tags')
    with op.batch_alter_table('publish_configurations', schema=None) as batch_op:
        batch_op.drop_index('idx_publish_config_profile')

    op.drop_table('publish_configurations')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index('idx_reset_token_user')
        batch_op.drop_index('idx_reset_token_hash')

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('normalization_rules', schema=None) as batch_op:
        batch_op.drop_index('idx_norm_rule_tag_group')
        batch_op.drop_index('idx_norm_rule_priority')
        batch_op.drop_index('idx_norm_rule_group')
        batch_op.drop_index('idx_norm_rule_enabled')

    op.drop_table('normalization_rules')
    with op.batch_alter_table('m3u_change_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_m3u_change_type')
        batch_op.drop_index('idx_m3u_change_time')
        batch_op.drop_index('idx_m3u_change_account_time')
        batch_op.drop_index('idx_m3u_change_account')

    op.drop_table('m3u_change_logs')
    with op.batch_alter_table('dummy_epg_channel_assignments', schema=None) as batch_op:
        batch_op.drop_index('idx_dummy_epg_profile_id')
        batch_op.drop_index('idx_dummy_epg_channel_id')

    op.drop_table('dummy_epg_channel_assignments')
    with op.batch_alter_table('auto_creation_executions', schema=None) as batch_op:
        batch_op.drop_index('idx_auto_exec_triggered_by')
        batch_op.drop_index('idx_auto_exec_status')
        batch_op.drop_index('idx_auto_exec_started')
        batch_op.drop_index('idx_auto_exec_rule')
        batch_op.drop_index('idx_auto_exec_mode')

    op.drop_table('auto_creation_executions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_user_external_id')
        batch_op.drop_index('idx_user_auth_provider')

    op.drop_table('users')
    with op.batch_alter_table('unique_client_connections', schema=None) as batch_op:
        batch_op.drop_index('idx_unique_client_ip_date')
        batch_op.drop_index('idx_unique_client_ip')
        batch_op.drop_index('idx_unique_client_date')
        batch_op.drop_index('idx_unique_client_channel_ip_date')
        batch_op.drop_index('idx_unique_client_channel_date')
        batch_op.drop_index('idx_unique_client_channel')

    op.drop_table('unique_client_connections')
    with op.batch_alter_table('task_schedules', schema=None) as batch_op:
        batch_op.drop_index('idx_task_schedule_task_id')
        batch_op.drop_index('idx_task_schedule_next_run')
        batch_op.drop_index('idx_task_schedule_enabled')

    op.drop_table('task_schedules')
    with op.batch_alter_table('task_executions', schema=None) as batch_op:
        batch_op.drop_index('idx_task_exec_task_id')
        batch_op.drop_index('idx_task_exec_status')
        batch_op.drop_index('idx_task_exec_started_at')

    op.drop_table('task_executions')
    with op.batch_alter_table('tag_groups', schema=None) as batch_op:
        batch_op.drop_index('idx_tag_group_name')
        batch_op.drop_index('idx_tag_group_builtin')

    op.drop_table('tag_groups')
    with op.batch_alter_table('stream_stats', schema=None) as batch_op:
        batch_op.drop_index('idx_stream_stats_stream_id')
        batch_op.drop_index('idx_stream_stats_probe_status')
        batch_op.drop_index('idx_stream_stats_last_probed')

    op.drop_table('stream_stats')
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_scheduled_task_next_run')
        batch_op.drop_index('idx_scheduled_task_id')
        batch_op.drop_index('idx_scheduled_task_enabled')

    op.drop_table('scheduled_tasks')
    op.drop_table('playlist_profiles')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notification_type')
        batch_op.drop_index('idx_notification_source')
        batch_op.drop_index('idx_notification_read')
        batch_op.drop_index('idx_notification_created_at')

    op.drop_table('notifications')
    with op.batch_alter_table('normalization_rule_groups', schema=None) as batch_op:
        batch_op.drop_index('idx_norm_group_priority')
        batch_op.drop_index('idx_norm_group_enabled')

    op.drop_table('normalization_rule_groups')
    with op.batch_alter_table('m3u_snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_m3u_snapshot_time')
        batch_op.drop_index('idx_m3u_snapshot_account_time')
        batch_op.drop_index('idx_m3u_snapshot_account')

    op.drop_table('m3u_snapshots')
    op.drop_table('m3u_digest_settings')
    with op.batch_alter_table('lookup_tables', schema=None) as batch_op:
        batch_op.drop_index('idx_lookup_table_name')

    op.drop_table('lookup_tables')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_journal_timestamp')
        batch_op.drop_index('idx_journal_category')
        batch_op.drop_index('idx_journal_action_type')

    op.drop_table('journal_entries')
    with op.batch_alter_table('hidden_channel_groups', schema=None) as batch_op:
        batch_op.drop_index('idx_hidden_group_id')

    op.drop_table('hidden_channel_groups')
    op.drop_table('ffmpeg_saved_configs')
    with op.batch_alter_table('ffmpeg_profiles', schema=None) as batch_op:
        batch_op.drop_index('idx_ffmpeg_profiles_created')

    op.drop_table('ffmpeg_profiles')
    with op.batch_alter_table('dummy_epg_profiles', schema=None) as batch_op:
        batch_op.drop_index('idx_dummy_epg_profile_enabled')

    op.drop_table('dummy_epg_profiles')
    op.drop_table('cloud_storage_targets')
    with op.batch_alter_table('channel_watch_stats', schema=None) as batch_op:
        batch_op.drop_index('idx_channel_watch_time')
        batch_op.drop_index('idx_channel_watch_count')
        batch_op.drop_index('idx_channel_watch_channel_id')

    op.drop_table('channel_watch_stats')
    with op.batch_alter_table('channel_popularity_scores', schema=None) as batch_op:
        batch_op.drop_index('idx_popularity_trend')
        batch_op.drop_index('idx_popularity_score')
        batch_op.drop_index('idx_popularity_rank')
        batch_op.drop_index('idx_popularity_channel')

    op.drop_table('channel_popularity_scores')
    with op.batch_alter_table('channel_bandwidth', schema=None) as batch_op:
        batch_op.drop_index('idx_channel_bandwidth_date')
        batch_op.drop_index('idx_channel_bandwidth_channel')
        batch_op.drop_index('idx_channel_bandwidth_bytes')

    op.drop_table('channel_bandwidth')
    with op.batch_alter_table('bandwidth_daily', schema=None) as batch_op:
        batch_op.drop_index('idx_bandwidth_daily_date')

    op.drop_table('bandwidth_daily')
    with op.batch_alter_table('auto_creation_rules', schema=None) as batch_op:
        batch_op.drop_index('idx_auto_rule_run_on_refresh')
        batch_op.drop_index('idx_auto_rule_priority')
        batch_op.drop_index('idx_auto_rule_m3u_account')
        batch_op.drop_index('idx_auto_rule_enabled_priority')
        batch_op.drop_index('idx_auto_rule_enabled')

    op.drop_table('auto_creation_rules')
    with op.batch_alter_table('alert_methods', schema=None) as batch_op:
        batch_op.drop_index('idx_alert_method_type')
        batch_op.drop_index('idx_alert_method_enabled')

    op.drop_table('alert_methods')
    # ### end Alembic commands ###
